[tool.poetry]
name = "dz-python-2"
version = "0.1.0"
description = ""
authors = ["Artem <132493257+ArtemSochi29@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
